version: '3.8'

services:
  db:
    build: ./db
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  init_db:
    build: ./init_db
    depends_on:
      db:
        condition: service_healthy

  app:
    build: ./app
    platform: linux/x86_64
    depends_on:
      db:
        condition: service_healthy
      init_db:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/info"]
      interval: 7s
      timeout: 5s
      retries: 5
    ports:
      - 8080:8080
    volumes:
      - ./app:/app

  dashboard:
    build: ./dashboard
    depends_on:
      app:
        condition: service_healthy
      init_db:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    ports:
      - 8050:8050
    volumes:
      - ./dashboard:/dashboard