version: '3.8'

services:
  db:
    build: ./db
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

  app:
    build: ./app
    depends_on:
      - db
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./app:/app