version: '3.8'

services:
  db:
    build: ./db
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  init_db:
    build: ./init_db
    depends_on:
      db:
        condition: service_healthy

  app:
    build: ./app
    depends_on:
      db:
        condition: service_healthy
      init_db:
        condition: service_completed_successfully
    ports:
      - 8080:8080
    volumes:
      - ./app:/app