version: '3'

services:
  fitpass-app:
    build:
      context: .
    ports:
      - "5432:5432"
      - "8050:8050"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fitpass
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    entrypoint: ["bash"]

volumes:
  postgres-data: