CREATE TABLE IF NOT EXISTS cdmx_studios (
    gym_id          VARCHAR(255),
    gym_name        VARCHAR(255),
    pro_status      INT,
    virtual_status  INT,
    class_minutes   VARCHAR(255),
    latitude        VARCHAR(255),
    longitude       VARCHAR(255),
    barre           FLOAT,
    box             FLOAT,
    crossfit        FLOAT,
    cycling         FLOAT,
    dance           FLOAT,
    ems             FLOAT,
    functional      FLOAT,
    gym             FLOAT,
    hiit            FLOAT,
    mma             FLOAT,
    pilates         FLOAT,
    pool            FLOAT,
    running         FLOAT,
    sports          FLOAT,
    virtual_class   FLOAT,
    wellness        FLOAT,
    yoga            FLOAT
);